[package]
name = "dove"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
debug = true

[dependencies]
clap = { version = "4.4.1", features = ["derive", "wrap_help", "env"] }
memmap2 = "0.7.1"
pulldown-cmark = "0.9.3"
askama = "0.12.0"
minify-html-onepass = "0.11.1"
css-minify = "0.3.1"
minify-js = "0.5.6"
mimalloc = { version = "0.1.39", default-features = false }

[features]
default = []
test-content = []
